keys:
  - &snix age1y348p6q290u7szhcdh8ser8vd2uuea0vfc3edd3ejnxhywjdzvxsg2uvcg

creation_rules:
  # Private secrets in ~/.secrets/
  - path_regex: .*/\.secrets/.*\.yaml$
    key_groups:
      - age:
          - *snix
