keys:
  # Add your age key here - generate with: age-keygen -o ~/.config/sops/age/keys.txt
  # - &user age1your_age_key_here
  
  # You can also use GPG keys
  # - &user pgp:YOURGPGFINGERPRINT

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          # - *user
        pgp:
          # - *user
  
  # Separate rules for different environments
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          # - *user
        pgp:
          # - *user