keys:
  - &user age1eeglpcf2lpmjnazddleqw3qgyhydfsv9karvc0nkshk7qz8vwskqxu4zx6

creation_rules:
  # Private secrets in ~/.secrets/
  - path_regex: .*/\.secrets/.*\.yaml$
    key_groups:
      - age:
          - *user
