# hosts/wintv/lib/kodi.ps1
# Kodi configuration and setup for WinTV media center

#Requires -RunAsAdministrator

$ErrorActionPreference = "Stop"

# =============================================================================
# Configuration Paths
# =============================================================================

function Get-KodiPaths {
    $appData = $env:APPDATA
    return @{
        Root = "$appData\Kodi"
        Userdata = "$appData\Kodi\userdata"
        Addons = "$appData\Kodi\addons"
        AddonData = "$appData\Kodi\userdata\addon_data"
        Database = "$appData\Kodi\userdata\Database"
        GuiSettings = "$appData\Kodi\userdata\guisettings.xml"
        AdvancedSettings = "$appData\Kodi\userdata\advancedsettings.xml"
        Sources = "$appData\Kodi\userdata\sources.xml"
    }
}

# =============================================================================
# Advanced Settings Generator
# =============================================================================
# Creates advancedsettings.xml for performance tuning and network settings

function Set-KodiAdvancedSettings {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    $paths = Get-KodiPaths

    # Ensure userdata directory exists
    if (-not (Test-Path $paths.Userdata)) {
        New-Item -ItemType Directory -Path $paths.Userdata -Force | Out-Null
    }

    $bufferSize = $Config.Performance.BufferSize
    $readFactor = $Config.Performance.ReadFactor

    $advancedSettings = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by WinTV - do not edit manually -->
<!-- Source: hosts/wintv/config.nix -->
<advancedsettings version="1.0">
    <!-- Network and buffering settings for smooth 4K playback -->
    <cache>
        <buffermode>1</buffermode>
        <memorysize>$bufferSize</memorysize>
        <readfactor>$readFactor</readfactor>
    </cache>

    <!-- Video playback settings -->
    <video>
        <ignoresecondsatstart>180</ignoresecondsatstart>
        <ignorepercentatend>8</ignorepercentatend>
        <playcountminimumpercent>90</playcountminimumpercent>
        <defaultplayer>VideoPlayer</defaultplayer>
    </video>

    <!-- GUI responsiveness -->
    <gui>
        <algorithmdirtyregions>3</algorithmdirtyregions>
        <nofliptimeout>0</nofliptimeout>
    </gui>

    <!-- Jellyfin optimization -->
    <network>
        <curlclienttimeout>60</curlclienttimeout>
        <curllowspeedtime>30</curllowspeedtime>
        <curlretries>3</curlretries>
        <httpproxytype>0</httpproxytype>
    </network>

    <!-- Disable RSS feeds for cleaner home screen -->
    <rss>
        <enabled>false</enabled>
    </rss>

    <!-- Logging - reduce for production -->
    <loglevel hide="true">0</loglevel>
</advancedsettings>
"@

    $advancedSettings | Out-File -FilePath $paths.AdvancedSettings -Encoding UTF8
    Write-Host "  Created: advancedsettings.xml" -ForegroundColor Green
}

# =============================================================================
# Skin/Add-on Installation
# =============================================================================

function Install-KodiRepository {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Name,
        [Parameter(Mandatory=$true)]
        [string]$Url,
        [Parameter(Mandatory=$true)]
        [string]$ZipName
    )

    $paths = Get-KodiPaths
    $tempDir = "$env:TEMP\kodi-repos"
    $zipPath = "$tempDir\$ZipName"

    if (-not (Test-Path $tempDir)) {
        New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
    }

    Write-Host "  Downloading $Name repository..." -ForegroundColor Yellow
    try {
        Invoke-WebRequest -Uri $Url -OutFile $zipPath -UseBasicParsing

        # Extract to addons directory
        Expand-Archive -Path $zipPath -DestinationPath $paths.Addons -Force
        Write-Host "  Installed: $Name repository" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "  Failed to install $Name repository: $_" -ForegroundColor Red
        return $false
    }
}

function Install-KodiAddon {
    param(
        [Parameter(Mandatory=$true)]
        [string]$AddonId,
        [Parameter(Mandatory=$true)]
        [string]$Repository
    )

    # Note: Kodi add-ons are best installed through the UI on first run
    # This function creates a marker file for the setup wizard
    $paths = Get-KodiPaths
    $markerDir = "$($paths.Userdata)\wintv-pending-addons"

    if (-not (Test-Path $markerDir)) {
        New-Item -ItemType Directory -Path $markerDir -Force | Out-Null
    }

    # Create marker file with addon info
    @{
        AddonId = $AddonId
        Repository = $Repository
        Timestamp = Get-Date -Format "o"
    } | ConvertTo-Json | Out-File -FilePath "$markerDir\$AddonId.json" -Encoding UTF8

    Write-Host "  Queued for installation: $AddonId" -ForegroundColor Cyan
}

# =============================================================================
# Jellyfin Configuration
# =============================================================================

function Set-JellyfinConfig {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    $paths = Get-KodiPaths
    $jellyfinDataDir = "$($paths.AddonData)\plugin.video.jellyfin"

    if (-not (Test-Path $jellyfinDataDir)) {
        New-Item -ItemType Directory -Path $jellyfinDataDir -Force | Out-Null
    }

    # Create initial Jellyfin settings with server URL
    # User will still need to authenticate on first run
    $serverUrl = $Config.Jellyfin.ServerUrl
    $syncMode = $Config.Jellyfin.SyncMode

    # Determine play mode based on sync setting
    $playMode = if ($syncMode -eq "native") { "Native" } else { "Addon" }

    $jellyfinSettings = @"
<?xml version="1.0" encoding="UTF-8"?>
<settings version="2">
    <!-- Jellyfin server configuration -->
    <!-- User authentication required on first run -->
    <setting id="server_address">$serverUrl</setting>
    <setting id="playback_mode">$playMode</setting>

    <!-- Native mode settings (sync to Kodi library) -->
    <setting id="sync_indicator" default="true">true</setting>
    <setting id="sync_during_play" default="true">true</setting>
    <setting id="enable_context_menu" default="true">true</setting>

    <!-- Performance -->
    <setting id="stream_bitrate" default="true">140000000</setting>
    <setting id="direct_stream" default="true">true</setting>
    <setting id="direct_play" default="true">true</setting>
    <setting id="transcode_h265" default="true">false</setting>
    <setting id="transcode_hi10p" default="true">false</setting>
</settings>
"@

    $jellyfinSettings | Out-File -FilePath "$jellyfinDataDir\settings.xml" -Encoding UTF8
    Write-Host "  Pre-configured: Jellyfin server URL ($serverUrl)" -ForegroundColor Green
    Write-Host "  NOTE: Login required on first Kodi launch" -ForegroundColor Yellow
}

# =============================================================================
# GUI Settings
# =============================================================================

function Set-KodiGuiSettings {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    $paths = Get-KodiPaths

    # Ensure userdata directory exists
    if (-not (Test-Path $paths.Userdata)) {
        New-Item -ItemType Directory -Path $paths.Userdata -Force | Out-Null
    }

    # Map skin names to Kodi addon IDs
    $skinMap = @{
        "estuary" = "skin.estuary"
        "arctic-horizon-2" = "skin.arctic.horizon.2"
        "arctic-zephyr-2" = "skin.arctic.zephyr.2"
        "aeon-nox-silvo" = "skin.aeon.nox.silvo"
        "titan-bingie" = "skin.titan.bingie"
    }

    # Map refresh rate settings
    $refreshRateMap = @{
        "off" = "0"
        "start-stop" = "1"
        "always" = "2"
    }

    # Map start window settings
    $startWindowMap = @{
        "home" = "10000"
        "movies" = "10501"
        "tvshows" = "10502"
        "music" = "10502"
        "videos" = "10025"
    }

    $skin = $skinMap[$Config.UI.Skin]
    $refreshRate = $refreshRateMap[$Config.Video.RefreshRateMatching]
    $startWindow = $startWindowMap[$Config.UI.StartWindow]
    $screensaverTimeout = $Config.UI.ScreensaverTimeout * 60  # Convert to seconds

    # Audio passthrough settings
    $audioPassthrough = if ($Config.Audio.Passthrough) { "true" } else { "false" }
    $ac3 = if ($Config.Audio.Formats -contains "ac3") { "true" } else { "false" }
    $eac3 = if ($Config.Audio.Formats -contains "eac3") { "true" } else { "false" }
    $truehd = if ($Config.Audio.Formats -contains "truehd") { "true" } else { "false" }
    $dts = if ($Config.Audio.Formats -contains "dts") { "true" } else { "false" }
    $dtshd = if ($Config.Audio.Formats -contains "dtshd") { "true" } else { "false" }

    # Note: Full guisettings.xml is complex and best modified incrementally
    # We create a partial settings file that Kodi will merge on first run

    $guiSettings = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- WinTV Kodi Settings - Applied on first run -->
<settings version="2">
    <!-- Look and feel -->
    <setting id="lookandfeel.skin" default="true">$skin</setting>
    <setting id="lookandfeel.startupwindow" default="true">$startWindow</setting>
    <setting id="lookandfeel.enablerssfeeds" default="true">false</setting>

    <!-- Screensaver -->
    <setting id="screensaver.mode" default="true">$($Config.UI.Screensaver)</setting>
    <setting id="screensaver.time" default="true">$screensaverTimeout</setting>
    <setting id="screensaver.usemusicvisinstead" default="true">false</setting>

    <!-- Video settings -->
    <setting id="videoplayer.adjustrefreshrate" default="true">$refreshRate</setting>
    <setting id="videoplayer.usedisplayasclock" default="true">true</setting>
    <setting id="videoplayer.stretch43" default="true">0</setting>

    <!-- Audio settings - passthrough -->
    <setting id="audiooutput.passthrough" default="true">$audioPassthrough</setting>
    <setting id="audiooutput.ac3passthrough" default="true">$ac3</setting>
    <setting id="audiooutput.eac3passthrough" default="true">$eac3</setting>
    <setting id="audiooutput.truehdpassthrough" default="true">$truehd</setting>
    <setting id="audiooutput.dtspassthrough" default="true">$dts</setting>
    <setting id="audiooutput.dtshdpassthrough" default="true">$dtshd</setting>

    <!-- Audio - Atmos/spatial -->
    <setting id="audiooutput.atmos" default="true">true</setting>
    <setting id="audiooutput.stereoupmix" default="true">false</setting>

    <!-- Playback -->
    <setting id="videoplayer.autoplaynextitem" default="true">2</setting>
    <setting id="videoplayer.seeksteps" default="true">10,30,60,180,300,600,1800</setting>

    <!-- Power/CEC -->
    <setting id="pvrpowermanagement.enabled" default="true">false</setting>
    <setting id="input.enablemouse" default="true">true</setting>
</settings>
"@

    $guiSettings | Out-File -FilePath "$($paths.Userdata)\wintv-settings.xml" -Encoding UTF8
    Write-Host "  Created: wintv-settings.xml (will be applied on first run)" -ForegroundColor Green
}

# =============================================================================
# First-Run Setup Script
# =============================================================================
# Creates a script that runs inside Kodi to complete setup

function Set-KodiFirstRunSetup {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    $paths = Get-KodiPaths
    $setupDir = "$($paths.Userdata)\wintv-setup"

    if (-not (Test-Path $setupDir)) {
        New-Item -ItemType Directory -Path $setupDir -Force | Out-Null
    }

    # Map skin to repository info
    $skinRepos = @{
        "arctic-horizon-2" = @{
            RepoUrl = "https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-3.5.zip"
            RepoId = "repository.jurialmunkey"
            SkinId = "skin.arctic.horizon.2"
        }
        "arctic-zephyr-2" = @{
            RepoUrl = "https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-3.5.zip"
            RepoId = "repository.jurialmunkey"
            SkinId = "skin.arctic.zephyr.2"
        }
        "titan-bingie" = @{
            RepoUrl = "https://github.com/realcopacetic/repository.copacetic/raw/main/repository.copacetic/repository.copacetic-1.0.2.zip"
            RepoId = "repository.copacetic"
            SkinId = "skin.titan.bingie"
        }
        "aeon-nox-silvo" = @{
            RepoUrl = "https://github.com/aeon-nox/aeon-nox.github.io/raw/master/aeon-nox-silvo/repository.aeon.nox.silvo-1.0.3.zip"
            RepoId = "repository.aeon.nox.silvo"
            SkinId = "skin.aeon.nox.silvo"
        }
    }

    # Create setup instructions file
    $setupInstructions = @"
WinTV Kodi First-Run Setup
===========================

Your Kodi has been pre-configured for optimal 4K HDR playback.

REQUIRED MANUAL STEPS:

1. INSTALL JELLYFIN ADD-ON:
   a. Go to Settings > File Manager > Add source
   b. Enter: https://repo.jellyfin.org/releases/client/kodi/
   c. Name it: Jellyfin
   d. Go to Settings > Add-ons > Install from zip file > Jellyfin
   e. Select: repository.jellyfin.kodi.zip
   f. Go to Install from repository > Jellyfin > Video add-ons
   g. Install: Jellyfin for Kodi
   h. When prompted, enter your Jellyfin credentials

2. INSTALL SKIN ($($Config.UI.Skin)):
$(if ($skinRepos.ContainsKey($Config.UI.Skin)) {
@"
   a. Go to Settings > File Manager > Add source
   b. Enter: $($skinRepos[$Config.UI.Skin].RepoUrl -replace '/[^/]+\.zip$', '/')
   c. Name it: $($skinRepos[$Config.UI.Skin].RepoId -replace 'repository\.', '')
   d. Go to Settings > Add-ons > Install from zip file
   e. Select the repository zip
   f. Go to Install from repository > find the skin
   g. Install: $($skinRepos[$Config.UI.Skin].SkinId)
"@
} else {
"   Using default Estuary skin - no additional installation needed"
})

3. CONFIGURE AUDIO OUTPUT:
   a. Go to Settings > System > Audio
   b. Set Audio output device to your TV/receiver
   c. Enable "Allow passthrough"
   d. Configure passthrough formats (AC3, E-AC3, TrueHD, DTS, DTS-HD)

Your pre-configured settings:
- Video: 4K HDR with refresh rate matching
- Audio: Full passthrough enabled (Atmos, DTS:X)
- Jellyfin: Server URL pre-configured ($($Config.Jellyfin.ServerUrl))
- Theme: $($Config.UI.Skin)

After completing these steps, restart Kodi for all settings to take effect.
"@

    $setupInstructions | Out-File -FilePath "$setupDir\SETUP-INSTRUCTIONS.txt" -Encoding UTF8

    # Also copy to desktop for easy access
    $desktopPath = [Environment]::GetFolderPath("Desktop")
    $setupInstructions | Out-File -FilePath "$desktopPath\Kodi-Setup-Instructions.txt" -Encoding UTF8

    Write-Host "  Created: Setup instructions (on Desktop)" -ForegroundColor Green
}

# =============================================================================
# Main Entry Point
# =============================================================================

function Initialize-Kodi {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    Write-Host ""
    Write-Host "[Kodi] Configuring media center..." -ForegroundColor Cyan

    # Create advanced settings for buffering/performance
    Set-KodiAdvancedSettings -Config $Config

    # Create GUI settings template
    Set-KodiGuiSettings -Config $Config

    # Pre-configure Jellyfin if enabled
    if ($Config.Jellyfin.Enable) {
        Set-JellyfinConfig -Config $Config
    }

    # Create first-run setup instructions
    Set-KodiFirstRunSetup -Config $Config

    Write-Host ""
    Write-Host "  Kodi configuration complete!" -ForegroundColor Green
    Write-Host "  See Desktop\Kodi-Setup-Instructions.txt for manual steps" -ForegroundColor Cyan
    Write-Host ""
}
