# profiles/security/sops-hm.nix
# Home Manager SOPS integration for user-level secrets
#
# This module manages:
#   - SOPS secrets decryption for Home Manager
#   - Environment variables from secrets
#
# Secrets are stored in ~/.secrets/secrets.yaml (encrypted with age)
# Decrypted secrets available at ~/.config/sops-nix/secrets/
#
# To add a new secret:
#   1. Add it to this module's sops.secrets
#   2. Encrypt it: sops ~/.secrets/secrets.yaml
#   3. Reference via config.sops.secrets.<name>.path
#
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.dotfiles.sops-hm;
  secretsDir = "${config.home.homeDirectory}/.secrets";
in
{
  options.dotfiles.sops-hm = {
    enable = lib.mkEnableOption "Home Manager SOPS secrets";

    secretsFile = lib.mkOption {
      type = lib.types.str;
      default = "${secretsDir}/secrets.yaml";
      description = "Path to the SOPS secrets file";
    };

    ageKeyFile = lib.mkOption {
      type = lib.types.str;
      default = "${secretsDir}/age-key.txt";
      description = "Path to the age private key for decryption";
    };
  };

  config = lib.mkIf cfg.enable {
    # SOPS configuration for Home Manager
    sops = {
      defaultSopsFile = cfg.secretsFile;
      defaultSopsFormat = "yaml";

      age.keyFile = cfg.ageKeyFile;

      # Define secrets - these will be decrypted to ~/.config/sops-nix/secrets/
      secrets = {
        # Infrastructure URLs (private, not truly secret)
        "services/ollama/baseURL" = { };
      };
    };

    # Export secrets as environment variables via session script
    # This runs at shell startup and exports decrypted values
    home.file.".config/sops-nix/load-secrets.sh" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Load SOPS secrets as environment variables
        # Generated by Home Manager - do not edit manually

        # Only load if secrets exist (allows graceful degradation)
        SECRETS_BASE="${config.sops.defaultSymlinkPath}"

        # Ollama base URL for OpenCode/Aider
        if [[ -f "$SECRETS_BASE/services/ollama/baseURL" ]]; then
          export OLLAMA_BASE_URL="$(cat "$SECRETS_BASE/services/ollama/baseURL")"
        fi
      '';
    };

    # Source the secrets loader in shell initialization
    programs.bash.initExtra = lib.mkIf config.programs.bash.enable ''
      # Load SOPS secrets as environment variables
      [[ -f ~/.config/sops-nix/load-secrets.sh ]] && source ~/.config/sops-nix/load-secrets.sh
    '';

    programs.zsh.initExtra = lib.mkIf config.programs.zsh.enable ''
      # Load SOPS secrets as environment variables
      [[ -f ~/.config/sops-nix/load-secrets.sh ]] && source ~/.config/sops-nix/load-secrets.sh
    '';

    programs.fish.interactiveShellInit = lib.mkIf config.programs.fish.enable ''
      # Load SOPS secrets as environment variables
      if test -f ~/.config/sops-nix/load-secrets.sh
        source ~/.config/sops-nix/load-secrets.sh
      end
    '';
  };
}
